version: '3.9'

services:
  app:
    image: cosmtrek/air:latest
    ports:
      - '9000:9000'
    volumes:
      - type: bind
        source: .
        target: /app
      - go-modules:/go/pkg/mod
    working_dir: /app
    depends_on:
      - database
    env_file:
      - '.env.docker'
    command: ["-c", "/app/.air.toml"]
  database:
    image: 'postgres:11.1-alpine'
    container_name: bill_split_db
    ports:
      - 5431:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env.docker'

volumes:
  go-modules:
  postgres:
